"""
The following program is a simple password generator which asks the user the amount of letters, symbmols and numbers they want in their generated password.
The first part of the code generates the password but in the order or letters being first, symbols being second and lastly numbers at the end of the password.
The second part however completely randomizes the entire password regardless of the type of character.
"""

import random

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Following Program will help you generate a strong password.")
nr_letters= int(input("How many letters would you like in your password?\n")) 
nr_symbols = int(input("How many symbols would you like?\n"))
nr_numbers = int(input("How many numbers would you like?\n"))

#Normal level where the order of the characters is not randomized.

password = ""
for i in range(nr_letters):
  randomLetter = random.choice(letters)
  password += randomLetter

for i in range(nr_symbols):
  randomSymbol = random.choice(numbers)
  password += randomSymbol

for i in range(nr_numbers):
  randomNumber = random.choice(symbols)
  password += randomNumber

print("\nNormal Password: " + password)


#Taking it bit to another level where entire order is randomized.

strongerPass = random.sample(password, len(password))
strongerPassword = ""
for char in strongerPass:
  strongerPassword += str(char)

print("Stronger Password: " + strongerPassword)




""" 
==============OTHER METHOD================
Can use one more method shuffle() to shuffle the password, but the password should be in the list data type format.
To convert that list to string, one can just simply use for loop adding each characted to an empty string declared before the loop.
"""




"""
===============YET ANOTHER METHOD===============

NOTE: Only useful if the user doesn't specify the amount of specific character they need

strongerPassword = ""
passwordSize = nr_letters + nr_numbers + nr_symbols


Here, we are intuitively adding the given lists in another list and then further generating a random number between 0 and 2 which will determine which list it will select.
That is passed through the choice funtciont where it will randomly pick out the character from that SPECIFIED LIST which was randomly generated by generating 0, 1 or 2 numbers using randint() function just before.


passwordRange = [letters, numbers, symbols]

for count in range(passwordSize):
  randomType = random.randint(0, 2)
  randomChar = random.choice(passwordRange[randomType])
  strongerPassword += randomChar

print("Stronger Password: " + strongerPassword)
"""
